### ISSUE TITLE
Safari does not show up in Browser.brands

### ISSUE THREAD

**Issue by wnstn** [honeycombio/honeycomb-opentelemetry-web#114]
**Versions**

Current version

**Steps to reproduce**

1. [Example query in Honeycomb](https://ui-dogfood.honeycomb.io/prod/environments/docs/datasets/docs/result/oNHz2mFcqGz)

**Additional context**

Browser.brands is populated in the instrumentation, but Safari doesn't seem to make it through the processor.

**Comment by wolfgangcodes** [comment]
This was addressed in #130 with the addition of `broswer.name`
