### ISSUE TITLE
`package.json` is missing `@opentelemetry/core` in `peerDependencies`

### ISSUE THREAD

**Issue by Aghassi** [honeycombio/honeycomb-opentelemetry-web#127]
**Versions**
0.1.1

**Steps to reproduce**

1. In a project using `pnpm` and `webpack` install this package without adding any additional dependencies
2. Attempt to import this package and bundle it with webpack
3. Webpack should throw and an error for not finding `@opentelemetry/core`. This is because this package never specifies it in package.json and thus will never be resolved.

**Additional context**
`pnpm` and newer versions of `yarn` require maintainers to specify packages they don't bundle but are expected to have as peer dependencies. Otherwise, you are relying on the dependency manager to `hoist` the dependency which is never guaranteed. It's best to specify these packages as peer dependencies with major ranges unless you need a specific version

**Comment by wolfgangcodes** [comment]
Hi @Aghassi! `@opentelemetry/core` was explicitly added as to `dependencies` in PR #136, so we'll track splitting `dependencies` from `peerDependencies`  in  issue https://github.com/honeycombio/honeycomb-opentelemetry-web/issues/126
