### ISSUE TITLE
Package BaggageSpanProcessor and DeterministicSampler to use in this repo

### ISSUE THREAD

**Issue by pkanal** [honeycombio/honeycomb-opentelemetry-web#13]
Talked with the Pipeline team and there are some shared components between the node and web distros, namely the `BaggageSpanProcessor` and the `DeterministicSampler`. We would like to have a repo that is separate from the node / web distros that packages these and the distros can depend on them.

**Comment by JamieDanielson** [comment]
For now we are going to copy the functionality here, and separate the package into a shared dependency later. I created 2 new issues linked to this, and removed this from the beta milestone.

**Comment by wolfgangcodes** [comment]
We'll eventually pickup `BaggageSpanProcessor` upstream and we'll address sharing `DeterministicSampler` if/when it becomes an issue. 😸
