### ISSUE TITLE
unable to do custom tracing with @opentelemetry/api@1.9.0 when honeycomb references 1.8.0 as a hard dependency

### ISSUE THREAD

**Issue by longility** [honeycombio/honeycomb-opentelemetry-web#172]
We should do something like this and expect consumers to install as peer dependency: https://github.com/open-telemetry/opentelemetry-js/blob/4fa7c1358e84287079a5cba95313d42b50cfcb91/experimental/packages/opentelemetry-sdk-node/package.json#L62-L66

**Versions**
"@honeycombio/opentelemetry-web": "0.3.0"

**Steps to reproduce**

1. install `"@opentelemetry/api": "1.9.0"` along with the honeycomb version mentioned above
2. add `console.log(trace.getTracerProvider());` after `sdk.start()` where sdk is an instance of `HoneycombWebSDK`
3. you will see that the delegate of the tracer provider does not point to the web tracer.

**Additional context**
So when we use `trace.getTracer('foo')` and do custom traces, it is considered a non-recording span because it is using the `trace` that is referencing 1.9.0 instead of 1.8.0 that the honeycomb lib is using as a hard dependency.

**Comment by wolfgangcodes** [comment]
Hi @longility thanks for opening this issue!  `@opentelemetry/api` version was updated to `~1.9.0` in the `0.4.0` release (#180). We are separately tracking separating dependencies and  peer dependencies here: https://github.com/honeycombio/honeycomb-opentelemetry-web/issues/126.
