### ISSUE TITLE
Make stacktrace useful when source code is not publicly exposed

### ISSUE THREAD

**Issue by longility** [honeycombio/honeycomb-opentelemetry-web#194]
**Is your feature request related to a problem? Please describe.**
When I report errors, my stacktrace is minified and obfuscated to where it is difficult to troubleshoot since we have sourcemaps turned off for production so we are not exposing our source code publicly.

**Describe the solution you'd like**
Be able to upload sourcemaps so that honeycomb can map properly something like Sentry or have a guide on best practice or approach that solves the problem.

**Describe alternatives you've considered**
Not familiar with other alternatives as I'm not an expert in this.

**Additional context**

**Comment by wolfgangcodes** [comment]
Thank @longility for opening this issue! We're looking into how we can improve the error diagnosing but that is likely to happen in another repository. I've made sure to share this ask with the right team, but since this issue isn't actionable for this repo I'm going to close this issue.
