### ISSUE TITLE
Why OTel based RUM is the best in frontend?

### ISSUE THREAD

**Issue by Jeevananthan-23** [honeycombio/honeycomb-opentelemetry-web#346]
Hi team, 

Really cool project and i'm also looking for RUM based project where i can trace user behavior in context of frontend observability.

Found Umami(Light weight JS lib), Posthog(well used across industries) and OTel based RUM product how it stand out why i chose it.

**Comment by wolfgangcodes** [comment]
Hi @Jeevananthan-23! You can check out the [README.md](https://github.com/honeycombio/honeycomb-opentelemetry-web/blob/main/README.md ) to see how you might use this SDK or if you see that there's something missing and want to open a PR you can check out the  [CONTRIBUTING.md](https://github.com/honeycombio/honeycomb-opentelemetry-web/blob/main/CONTRIBUTING.md) and [DEVELOPING.md](https://github.com/honeycombio/honeycomb-opentelemetry-web/blob/main/DEVELOPING.md) guides!
