### ISSUE TITLE
test distro with common web frameworks

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-web#44]
Test distro with common web frameworks and document compatibility. Outcome is not necessarily to fix issues that arise, but to document current compatibility and determine from there.

Probably top priority:

- create-react-app
- next.js
- vanilla js
- vanilla js with webpack
- vanilla js with esbuild

Next priority:
- angular
- vue
- svelte
- remix
- astro

**Comment by JamieDanielson** [comment]
Unassigning myself for now as I'm not actively testing frameworks, will come back to this

**Comment by JamieDanielson** [comment]
- [x] create-react-app: [JamieDanielson/otel-web-my-create-react-app](https://github.com/JamieDanielson/otel-web-my-create-react-app)
- [ ] next.js 
- [ ] vanilla js
- [x] vanilla js with webpack [examples/custom-with-collector](https://github.com/honeycombio/honeycomb-opentelemetry-web/tree/main/examples/custom-with-collector-ts) - note this app is in typescript
- [x] vanilla js with esbuild: [examples/hello-world-web](https://github.com/honeycombio/honeycomb-opentelemetry-web/tree/main/examples/hello-world-web)

**Comment by ahrbnsn** [comment]
late to the party (apologies), but i'd like to nominate remix & astro to the mix

**Comment by JamieDanielson** [comment]
- [x] vue: [JamieDanielson/otel-web-my-create-vue-app](https://github.com/JamieDanielson/otel-web-my-create-vue-app)

**Comment by JamieDanielson** [comment]
Angular latest (^17.2.0) cannot install the auto-instrumentations for web because of a conflicting peer dependency on zone.js. That is on the radar to be updated upstream but will require a newer version of the auto-instrumentations package.

```txt
While resolving: my-angular-app@0.0.0
Found: zone.js@0.14.4
node_modules/zone.js
  zone.js@"~0.14.3" from the root project

Could not resolve dependency:
peer zone.js@"0.11.4" from @opentelemetry/auto-instrumentations-web@0.36.0
node_modules/@opentelemetry/auto-instrumentations-web
  @opentelemetry/auto-instrumentations-web@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

adding the SDK on its own without instrumentations does work right now though.

- [ ] angular: [JamieDanielson/otel-web-my-angular-app](https://github.com/JamieDanielson/otel-web-my-angular-app)

**Comment by JamieDanielson** [comment]
- [x] svelte: [JamieDanielson/otel-web-my-svelte-app](https://github.com/JamieDanielson/otel-web-my-svelte-app)

**Comment by wolfgangcodes** [comment]
Hey @JamieDanielson, I don't think we can take on the maintenance burden of a large example repo at this time, but I could see something like this being very useful and might even be better served upstream. I'm going to close this for now as we can consider revisiting down the road if we feel there's still a need.
