### ISSUE TITLE
[feat] Add ConsoleSpanExporter easy-button for local dev

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-web#73]
**Is your feature request related to a problem? Please describe.**

Sometimes it's nice to see what the output of telemetry would be, without needing to send anywhere. Debug only logs to stdout if it's successfully exported, and otherwise you need to manually add in a ConsoleSpan Exporter.

**Describe the solution you'd like**

Maybe a ConsoleSpanExporter easy-button. Since debug only logs if something is successfully exported, a "dev" option could ignore everything else and just always send to stdout and never try to export elsewhere

**Describe alternatives you've considered**

Just rely on manually adding ConsoleSpanExporter and/or spinning up a collector. Or another tool might work just as well or better for this and I just don't have it in mind right now!

**Additional context**

[Comment thread](https://github.com/honeycombio/honeycomb-opentelemetry-web/pull/72#discussion_r1489766865) on PR 72

>if we drop everything, do we still get logs if debug is true? like could someone set it to zero to see what events would be sent but not actually send events over the wire?

**Comment by pkanal** [comment]
This is possible with the addition of #303
