### ISSUE TITLE
Add session id to the baggage in baggage span processor?

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-web#75]
do you think it'd be useful to add the session id to the baggage? thinking it would help link server-side traces to specific sessions

_Originally posted by @ahrbnsn in https://github.com/honeycombio/honeycomb-opentelemetry-web/pull/74#discussion_r1490203464_

**Comment by JamieDanielson** [comment]
I don't think this is possible today with how the context API works in JS. In some languages like Python and Ruby, you can attach and detach context. In JS, the context is scoped and you use callbacks to apply a specific context.

I started on [a branch](https://github.com/honeycombio/honeycomb-opentelemetry-web/compare/main...jamie.session-id) that has some ideas and comments in one commit, and then a possible way of supplying functions for other types of IDs that may be useful, added as span attributes using a new span processor.

**Comment by wolfgangcodes** [comment]
Thanks @JamieDanielson for your investigation! We can reopen or file a new issue as the JS Context landscape evolves, but currently this is not we're actively taking action on this issue.
