### ISSUE TITLE
Feat: Document how to add Amplitude Session ID

### ISSUE THREAD

**Issue by wnstn** [honeycombio/honeycomb-opentelemetry-web#78]
Users want to grab their Amplitude session id and add it as a resource attribute on spans. This ticket is to remind us to figure out the code for doing that, which will go into our Documentation (on the docs site).

Please feel free to see if there's other things we should add from the Amplitude API! ideas are welcome.

**Comment by wolfgangcodes** [comment]
Could this be achieved with the the Multiple Span Processor added in #212 ?
