### ISSUE TITLE
Use Case discussion

### ISSUE THREAD

**Issue by wnstn** [honeycombio/honeycomb-opentelemetry-web#86]
In order to discuss our default setup and APIs in the package, here's a list of use cases I believe users will want to pursue in the course of using the package.

The goal of listing the use-cases is to discuss whether or not the goal can be achieved, and to have discussions about how it happens via APIs/code paths, so we can determine if we want to improve things!

### 1: I want to add attributes that are relevant to my company

I've got the instrumentation installed, and now I think adding some attributes to all events would help me filter the data. Some example attributes:
- Customer ID
- Account/Team ID
- Billing Plan (free, paid, enterprise)
- Sentry Session ID
- FullStory Session ID
- Amplitude Session ID

frustratingly, this info is a bit scattered in my app, so I may need to add these attributes in different places in my codebase.

### 2: I want to add attributes that aren't available when the tracing is instantiated

Thanks to goddamn React, I have to wait until my SSR payload is delivered and hydrated before I can kick of some session-specific requests to update state. Yes I know it sucks. But anyways, tracing is instantiated in the SSR delivered bundle, and depending on network speeds some info isn't available until 5 seconds later. Ideally, this info is available on all events/traces. Examples are:

- Customer ID
- Contents of their shopping cart
- User specific info (feature flags, entitlements)

Once this info is available, I'd like an API to add it to my spans. In an ideal world, all spans have been held until I get this info, up to a timeout I set, so that any spans generated before my callback hell ends can get the proper attributes. If that's NOT possible, I'd still like to make sure all future spans have it.

### 3: I want to turn off noisy events that aren't relevant to our current needs

When we got Honeycomb RUM, we had some issues with Core Web Vitals, but now those issues are solved permanently (ha I wish). Anyways, things are in range, and we monitor the metrics via a Google tool, so we would like to free up event usage for other telemetry. How can I turn off Core Web Vitals?

Actually wow, the GetResource spans are quite noisy because we're using HTTP2 and also have 18 third party integrations on our site, can we:
1. turn them all off as our team goals aren't focused on page performance and so this data is irrelevant
2. build a ruleset for ignoring requests sent to specific domains. For this one, is it possible to do without a collector, or do I need a collector?

### 4: omg this instrumentation is so great, I want to add more!

I want to add custom events inside my components, how can I do that? two examples of things I'm thinking about:

1. I want to do something like Ashley's performance measuring in Hound: I want to know when a react component instantiates and then know when it's finished rendering. is this a span? two linked events?  how can I use this to test performance of a specific component.
2. On a simpler level, I have a code path that seems buggy but we aren't quite sure when it executes. I'd like to fire off a custom event? trace? span? when it executes so I can start making sense of it.

### 5: I would like to create a helper function in my design system that adds a bunch of component level info to spans

This OTel thing is great, I would like to make it as easy as possible for users of my design system to use. In my head, this means every design system component is ready to go with OTel, the dev just needs to register the component with custom info about the context it's being used in. How can I create a simple function (or a constructor?) that accepts a JS object and applies the contents of that object to the events that are wired up in the component (like, button clicks, API calls, etc).

Data my users might add:
- Component name
- team owner
- context passed in from parent components

---

ok wow sorry this is so much and i was needing some creative writing work so i went a bit silly. ask me questions for clarification!

**Comment by ethangodt** [comment]
I'm pretty interested in all of these things. Was this used as a guide for documentation? Are the answers to these prompts anywhere online?

**Comment by wnstn** [comment]
Hey @ethangodt thanks for the comment! Some of these are still in progress but here's what we've got:

For number 1, you can [Resource Attributes](https://docs.honeycomb.io/get-started/start-building/web/#add-application-specific-resource-attributes), anything passed into that object will be available on every single span your app emits.

Number 2 is still unsolved; OTel assumes Resource Spans are all available at instantiation so we're still working on that.

Number 3 needs some more documentation, but we do offer some levers, if there's a specific type of event you don't want let us know, I don't have links handy for that. 

Number 4 is [Custom Instrumentation](https://docs.honeycomb.io/send-data/javascript-browser/honeycomb-distribution/#add-custom-instrumentation), go wild with whatever events you want to add (and they will have all Resource Attributes attached for correlation/querying).

Number 5 is also unsolved, we're working to build a roadmap but don't have it prioritized quite yet.

**Comment by ethangodt** [comment]
@wnstn thanks for the response. This helps!

**Comment by wolfgangcodes** [comment]
Thanks @wnstn and @ethangodt for the discussion! I think a lot of these ideas are captured elsewhere and/or have already made it into one of our beta releases.
